title: VRR OIV
description: Tekentool bereikbaarheidskaarten voor de VRR
show_downloads: true
google_analytics:
remote_theme: rundocs/jekyll-rtd-theme
lang: nl
readme_index:
  with_frontmatter: true
translate:
  # shortcodes
  danger: Let op
  note: Opmerking
  tip: Tip
  warning: Waarschuwing
  # 404
  not_found: Pagina niet gevonden
  # copyright
  revision: Revisie
  # search
  searching: Zoeken
  search: Zoek
  search_docs: Zoek documentatie
  search_results: Zoek resultaten
  search_results_found: # the "#" in this translate will replaced with results size!
  search_results_not_found: Uw zoekopdracht heeft geen resultaten opgeleverd